name: Build, Test, and Release Noctua

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with timestamp
        run: |
          $currentDate = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
          pyinstaller --name "noctua_$($currentDate)" --onefile --add-data "resources/images;resources/images" src/noctua/main.py
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: noctua-exe
          path: dist/noctua_*.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: noctua-exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: noctua_*.exe
          tag_name: "v${{ github.run_id }}-${{ github.run_number }}"
          name: "Release ${{ github.run_id }}-${{ github.run_number }}"
          body: "Automated release of Noctua version ${{ github.run_id }}-${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
